coverage_service: coveralls
xcodeproj: BMSPush.xcodeproj
workspace: BMSPush.xcworkspace
scheme: BMSPush
ignore:
  - Tests/*
  - Source/BMSRichPushNotificationOptions.swift
  - Source/BMSPushClient.swift
