language: objective-c
env:
  global:
  - PATH=/usr/local/bin:$PATH
  - LC_TYPE=en_US.UTF-8
matrix:
  include:
    - os: osx
      osx_image: xcode7.3
      sudo: required
script:
  - pod setup
  - pod spec lint --allow-warnings
  - carthage update
  - xcodebuild -scheme 'BMSPush' clean build CODE_SIGN_IDENTITY= CODE_SIGNING_REQUIRED=NO
  - xcodebuild test -scheme 'BMSPushTests' -destination 'platform=iOS Simulator,name=iPhone 6s'

